<?php

return [
    'pid_start' => 5000,

    'visa_types' => [
        'Study visa',
        'Visitor Visa',
        'PR',
        'Spouse open Work Permit',
        'Family Sponsorship Permit',
        'IELTS',
        'Spoken English',
        'TOEFL',
        'Life Skills',
        'Language Certificate',
        'PTE',
        'Closed Work Permit(LMIA)',
        'Super Visa',
        'Duolingo',
        'Interview',
        'CAIPS/ATIPS',
        'WES',
        'Useless Lead',
        'work permit',
    ],

    'process_timelines' => [
        'Study visa' => [
            ['key' => 'offer-letter-applied', 'label' => 'Offer letter applied'],
            ['key' => 'col-received', 'label' => 'COL received'],
            ['key' => 'arranging-financials', 'label' => 'Arranging financials'],
            ['key' => 'financials-sent-to-uni', 'label' => 'Financials sent to uni'],
            ['key' => 'preparing-interview', 'label' => 'Preparing Interview'],
            ['key' => 'uncol-received', 'label' => 'UnCOL received'],
            ['key' => 'file-lodged', 'label' => 'File lodged'],
            ['key' => 'visa-approved', 'label' => 'Visa approved'],
            ['key' => 'video-shot', 'label' => 'Video shot'],
        ],
    ],

    'statuses_requiring_follow_up' => [
        'interested',
        'wv again',
        'pursuing ielts/pte',
        'arranging docs',
        'in process',
    ],

    'statuses_no_follow_up' => [
        'not eligible',
        'plan drop',
    ],

    'customer_statuses' => [
        'assigned',
        'interested',
        'pursuing ielts/pte',
        'in process',
        'not eligible',
        'plan drop',
        'will visit',
        'jfi',
    ],

    'remark_statuses' => [
        'interested',
        'pursuing ielts/pte',
        'in process',
        'not eligible',
        'plan drop',
        'will visit',
        'jfi',
    ],

    'visiting_client_statuses' => [
        'will visit',
        'interested',
    ],

    'telecaller_statuses' => [
        'will visit',
        'interested',
    ],

    'genders' => ['male', 'female'],

    'marital_statuses' => ['single', 'married', 'divorced'],

    'gap_options' => [
        'No GAP',
        '1 year',
        '2 years',
        '3 years',
        '4 years',
        '5 years',
        '6+ years',
    ],

    'english_exams' => [
        'IELTS',
        'PTE',
        'CELPIP',
        'TOEFL',
        'Life Skills',
        'Duolingo',
        'UKVI',
    ],

    'google_chat_notification_types' => [
        'remarks' => [
            'label' => 'Remarks and status updates',
            'description' => 'Messages sent when someone adds a customer remark or updates status from remarks.',
        ],
        'bell_new_case_assigned' => [
            'label' => 'Bell: New case assigned',
            'description' => 'Google Chat copy of bell notifications for newly assigned cases.',
        ],
        'bell_customer_updated' => [
            'label' => 'Bell: Customer updated',
            'description' => 'Google Chat copy of bell notifications when customer fields are changed.',
        ],
        'bell_remark_tagged' => [
            'label' => 'Bell: User tagged in remark',
            'description' => 'Google Chat copy of bell notifications created by @mentions in remarks.',
        ],
        'bell_follow_up_reminder' => [
            'label' => 'Bell: Follow-up reminder',
            'description' => 'Google Chat copy of bell notifications for follow-up reminders.',
        ],
        'bell_other' => [
            'label' => 'Bell: Other notifications',
            'description' => 'Google Chat copy of any other bell notification not listed above.',
        ],
        'activity_logs' => [
            'label' => 'Activity logs',
            'description' => 'Google Chat messages generated from CRM activity logs, such as customer, document, fee, and admin changes.',
        ],
    ],

    'countries' => [
    'afghanistan' => 'Afghanistan',
    'albania' => 'Albania',
    'algeria' => 'Algeria',
    'andorra' => 'Andorra',
    'angola' => 'Angola',
    'antigua_and_barbuda' => 'Antigua and Barbuda',
    'argentina' => 'Argentina',
    'armenia' => 'Armenia',
    'australia' => 'Australia',
    'austria' => 'Austria',
    'azerbaijan' => 'Azerbaijan',
    'bahamas' => 'Bahamas',
    'bahrain' => 'Bahrain',
    'bangladesh' => 'Bangladesh',
    'barbados' => 'Barbados',
    'belarus' => 'Belarus',
    'belgium' => 'Belgium',
    'belize' => 'Belize',
    'benin' => 'Benin',
    'bhutan' => 'Bhutan',
    'bolivia' => 'Bolivia',
    'bosnia_and_herzegovina' => 'Bosnia and Herzegovina',
    'botswana' => 'Botswana',
    'brazil' => 'Brazil',
    'brunei' => 'Brunei',
    'bulgaria' => 'Bulgaria',
    'burkina_faso' => 'Burkina Faso',
    'burundi' => 'Burundi',
    'cabo_verde' => 'Cabo Verde',
    'cambodia' => 'Cambodia',
    'cameroon' => 'Cameroon',
    'canada' => 'Canada',
    'central_african_republic' => 'Central African Republic',
    'chad' => 'Chad',
    'chile' => 'Chile',
    'china' => 'China',
    'colombia' => 'Colombia',
    'comoros' => 'Comoros',
    'congo' => 'Republic of the Congo',
    'costa_rica' => 'Costa Rica',
    'croatia' => 'Croatia',
    'cuba' => 'Cuba',
    'cyprus' => 'Cyprus',
    'czechia' => 'Czechia',
    'democratic_republic_of_congo' => 'Democratic Republic of the Congo',
    'denmark' => 'Denmark',
    'djibouti' => 'Djibouti',
    'dominica' => 'Dominica',
    'dominican_republic' => 'Dominican Republic',
    'ecuador' => 'Ecuador',
    'egypt' => 'Egypt',
    'el_salvador' => 'El Salvador',
    'equatorial_guinea' => 'Equatorial Guinea',
    'eritrea' => 'Eritrea',
    'estonia' => 'Estonia',
    'eswatini' => 'Eswatini',
    'ethiopia' => 'Ethiopia',
    'fiji' => 'Fiji',
    'finland' => 'Finland',
    'france' => 'France',
    'gabon' => 'Gabon',
    'gambia' => 'Gambia',
    'georgia' => 'Georgia',
    'germany' => 'Germany',
    'ghana' => 'Ghana',
    'greece' => 'Greece',
    'grenada' => 'Grenada',
    'guatemala' => 'Guatemala',
    'guinea' => 'Guinea',
    'guinea_bissau' => 'Guinea-Bissau',
    'guyana' => 'Guyana',
    'haiti' => 'Haiti',
    'honduras' => 'Honduras',
    'hungary' => 'Hungary',
    'iceland' => 'Iceland',
    'india' => 'India',
    'indonesia' => 'Indonesia',
    'iran' => 'Iran',
    'iraq' => 'Iraq',
    'ireland' => 'Ireland',
    'israel' => 'Israel',
    'italy' => 'Italy',
    'ivory_coast' => 'Ivory Coast',
    'jamaica' => 'Jamaica',
    'japan' => 'Japan',
    'jordan' => 'Jordan',
    'kazakhstan' => 'Kazakhstan',
    'kenya' => 'Kenya',
    'kiribati' => 'Kiribati',
    'kuwait' => 'Kuwait',
    'kyrgyzstan' => 'Kyrgyzstan',
    'laos' => 'Laos',
    'latvia' => 'Latvia',
    'lebanon' => 'Lebanon',
    'lesotho' => 'Lesotho',
    'liberia' => 'Liberia',
    'libya' => 'Libya',
    'liechtenstein' => 'Liechtenstein',
    'lithuania' => 'Lithuania',
    'luxembourg' => 'Luxembourg',
    'madagascar' => 'Madagascar',
    'malawi' => 'Malawi',
    'malaysia' => 'Malaysia',
    'maldives' => 'Maldives',
    'mali' => 'Mali',
    'malta' => 'Malta',
    'marshall_islands' => 'Marshall Islands',
    'mauritania' => 'Mauritania',
    'mauritius' => 'Mauritius',
    'mexico' => 'Mexico',
    'micronesia' => 'Micronesia',
    'moldova' => 'Moldova',
    'monaco' => 'Monaco',
    'mongolia' => 'Mongolia',
    'montenegro' => 'Montenegro',
    'morocco' => 'Morocco',
    'mozambique' => 'Mozambique',
    'myanmar' => 'Myanmar',
    'namibia' => 'Namibia',
    'nauru' => 'Nauru',
    'nepal' => 'Nepal',
    'netherlands' => 'Netherlands',
    'new_zealand' => 'New Zealand',
    'nicaragua' => 'Nicaragua',
    'niger' => 'Niger',
    'nigeria' => 'Nigeria',
    'north_korea' => 'North Korea',
    'north_macedonia' => 'North Macedonia',
    'norway' => 'Norway',
    'oman' => 'Oman',
    'pakistan' => 'Pakistan',
    'palau' => 'Palau',
    'palestine' => 'Palestine',
    'panama' => 'Panama',
    'papua_new_guinea' => 'Papua New Guinea',
    'paraguay' => 'Paraguay',
    'peru' => 'Peru',
    'philippines' => 'Philippines',
    'poland' => 'Poland',
    'portugal' => 'Portugal',
    'qatar' => 'Qatar',
    'romania' => 'Romania',
    'russia' => 'Russia',
    'rwanda' => 'Rwanda',
    'saint_kitts_and_nevis' => 'Saint Kitts and Nevis',
    'saint_lucia' => 'Saint Lucia',
    'saint_vincent_and_the_grenadines' => 'Saint Vincent and the Grenadines',
    'samoa' => 'Samoa',
    'san_marino' => 'San Marino',
    'sao_tome_and_principe' => 'Sao Tome and Principe',
    'saudi_arabia' => 'Saudi Arabia',
    'senegal' => 'Senegal',
    'serbia' => 'Serbia',
    'seychelles' => 'Seychelles',
    'sierra_leone' => 'Sierra Leone',
    'singapore' => 'Singapore',
    'slovakia' => 'Slovakia',
    'slovenia' => 'Slovenia',
    'solomon_islands' => 'Solomon Islands',
    'somalia' => 'Somalia',
    'south_africa' => 'South Africa',
    'south_korea' => 'South Korea',
    'south_sudan' => 'South Sudan',
    'spain' => 'Spain',
    'sri_lanka' => 'Sri Lanka',
    'sudan' => 'Sudan',
    'suriname' => 'Suriname',
    'sweden' => 'Sweden',
    'switzerland' => 'Switzerland',
    'syria' => 'Syria',
    'tajikistan' => 'Tajikistan',
    'tanzania' => 'Tanzania',
    'thailand' => 'Thailand',
    'timor_leste' => 'Timor-Leste',
    'togo' => 'Togo',
    'tonga' => 'Tonga',
    'trinidad_and_tobago' => 'Trinidad and Tobago',
    'tunisia' => 'Tunisia',
    'turkey' => 'Turkey',
    'turkmenistan' => 'Turkmenistan',
    'tuvalu' => 'Tuvalu',
    'uganda' => 'Uganda',
    'ukraine' => 'Ukraine',
    'uae' => 'United Arab Emirates',
    'uk' => 'United Kingdom',
    'usa' => 'United States',
    'uruguay' => 'Uruguay',
    'uzbekistan' => 'Uzbekistan',
    'vanuatu' => 'Vanuatu',
    'vatican_city' => 'Vatican City',
    'venezuela' => 'Venezuela',
    'vietnam' => 'Vietnam',
    'yemen' => 'Yemen',
    'zambia' => 'Zambia',
    'zimbabwe' => 'Zimbabwe',
],

    'country_iso' => [
    'afghanistan' => 'af',
    'albania' => 'al',
    'algeria' => 'dz',
    'andorra' => 'ad',
    'angola' => 'ao',
    'antigua_and_barbuda' => 'ag',
    'argentina' => 'ar',
    'armenia' => 'am',
    'australia' => 'au',
    'austria' => 'at',
    'azerbaijan' => 'az',
    'bahamas' => 'bs',
    'bahrain' => 'bh',
    'bangladesh' => 'bd',
    'barbados' => 'bb',
    'belarus' => 'by',
    'belgium' => 'be',
    'belize' => 'bz',
    'benin' => 'bj',
    'bhutan' => 'bt',
    'bolivia' => 'bo',
    'bosnia_and_herzegovina' => 'ba',
    'botswana' => 'bw',
    'brazil' => 'br',
    'brunei' => 'bn',
    'bulgaria' => 'bg',
    'burkina_faso' => 'bf',
    'burundi' => 'bi',
    'cabo_verde' => 'cv',
    'cambodia' => 'kh',
    'cameroon' => 'cm',
    'canada' => 'ca',
    'central_african_republic' => 'cf',
    'chad' => 'td',
    'chile' => 'cl',
    'china' => 'cn',
    'colombia' => 'co',
    'comoros' => 'km',
    'congo' => 'cg',
    'costa_rica' => 'cr',
    'croatia' => 'hr',
    'cuba' => 'cu',
    'cyprus' => 'cy',
    'czechia' => 'cz',
    'democratic_republic_of_congo' => 'cd',
    'denmark' => 'dk',
    'djibouti' => 'dj',
    'dominica' => 'dm',
    'dominican_republic' => 'do',
    'ecuador' => 'ec',
    'egypt' => 'eg',
    'el_salvador' => 'sv',
    'equatorial_guinea' => 'gq',
    'eritrea' => 'er',
    'estonia' => 'ee',
    'eswatini' => 'sz',
    'ethiopia' => 'et',
    'fiji' => 'fj',
    'finland' => 'fi',
    'france' => 'fr',
    'gabon' => 'ga',
    'gambia' => 'gm',
    'georgia' => 'ge',
    'germany' => 'de',
    'ghana' => 'gh',
    'greece' => 'gr',
    'grenada' => 'gd',
    'guatemala' => 'gt',
    'guinea' => 'gn',
    'guinea_bissau' => 'gw',
    'guyana' => 'gy',
    'haiti' => 'ht',
    'honduras' => 'hn',
    'hungary' => 'hu',
    'iceland' => 'is',
    'india' => 'in',
    'indonesia' => 'id',
    'iran' => 'ir',
    'iraq' => 'iq',
    'ireland' => 'ie',
    'israel' => 'il',
    'italy' => 'it',
    'ivory_coast' => 'ci',
    'jamaica' => 'jm',
    'japan' => 'jp',
    'jordan' => 'jo',
    'kazakhstan' => 'kz',
    'kenya' => 'ke',
    'kiribati' => 'ki',
    'kuwait' => 'kw',
    'kyrgyzstan' => 'kg',
    'laos' => 'la',
    'latvia' => 'lv',
    'lebanon' => 'lb',
    'lesotho' => 'ls',
    'liberia' => 'lr',
    'libya' => 'ly',
    'liechtenstein' => 'li',
    'lithuania' => 'lt',
    'luxembourg' => 'lu',
    'madagascar' => 'mg',
    'malawi' => 'mw',
    'malaysia' => 'my',
    'maldives' => 'mv',
    'mali' => 'ml',
    'malta' => 'mt',
    'marshall_islands' => 'mh',
    'mauritania' => 'mr',
    'mauritius' => 'mu',
    'mexico' => 'mx',
    'micronesia' => 'fm',
    'moldova' => 'md',
    'monaco' => 'mc',
    'mongolia' => 'mn',
    'montenegro' => 'me',
    'morocco' => 'ma',
    'mozambique' => 'mz',
    'myanmar' => 'mm',
    'namibia' => 'na',
    'nauru' => 'nr',
    'nepal' => 'np',
    'netherlands' => 'nl',
    'new_zealand' => 'nz',
    'nicaragua' => 'ni',
    'niger' => 'ne',
    'nigeria' => 'ng',
    'north_korea' => 'kp',
    'north_macedonia' => 'mk',
    'norway' => 'no',
    'oman' => 'om',
    'pakistan' => 'pk',
    'palau' => 'pw',
    'palestine' => 'ps',
    'panama' => 'pa',
    'papua_new_guinea' => 'pg',
    'paraguay' => 'py',
    'peru' => 'pe',
    'philippines' => 'ph',
    'poland' => 'pl',
    'portugal' => 'pt',
    'qatar' => 'qa',
    'romania' => 'ro',
    'russia' => 'ru',
    'rwanda' => 'rw',
    'saint_kitts_and_nevis' => 'kn',
    'saint_lucia' => 'lc',
    'saint_vincent_and_the_grenadines' => 'vc',
    'samoa' => 'ws',
    'san_marino' => 'sm',
    'sao_tome_and_principe' => 'st',
    'saudi_arabia' => 'sa',
    'senegal' => 'sn',
    'serbia' => 'rs',
    'seychelles' => 'sc',
    'sierra_leone' => 'sl',
    'singapore' => 'sg',
    'slovakia' => 'sk',
    'slovenia' => 'si',
    'solomon_islands' => 'sb',
    'somalia' => 'so',
    'south_africa' => 'za',
    'south_korea' => 'kr',
    'south_sudan' => 'ss',
    'spain' => 'es',
    'sri_lanka' => 'lk',
    'sudan' => 'sd',
    'suriname' => 'sr',
    'sweden' => 'se',
    'switzerland' => 'ch',
    'syria' => 'sy',
    'tajikistan' => 'tj',
    'tanzania' => 'tz',
    'thailand' => 'th',
    'timor_leste' => 'tl',
    'togo' => 'tg',
    'tonga' => 'to',
    'trinidad_and_tobago' => 'tt',
    'tunisia' => 'tn',
    'turkey' => 'tr',
    'turkmenistan' => 'tm',
    'tuvalu' => 'tv',
    'uganda' => 'ug',
    'ukraine' => 'ua',
    'uae' => 'ae',
    'uk' => 'gb',
    'usa' => 'us',
    'uruguay' => 'uy',
    'uzbekistan' => 'uz',
    'vanuatu' => 'vu',
    'vatican_city' => 'va',
    'venezuela' => 've',
    'vietnam' => 'vn',
    'yemen' => 'ye',
    'zambia' => 'zm',
    'zimbabwe' => 'zw',
],
];
