<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fee Receipt {{ $receiptLog->receipt_no }}</title>
    <link href="{{ asset('vendor/bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <style>
        body {
            background: #f4f6f9;
            color: #0f172a;
            font-family: Arial, sans-serif;
        }
        .receipt-page {
            max-width: 860px;
            margin: 24px auto;
            background: #fff;
            border: 1px solid #e2e8f0;
            padding: 32px;
        }
        .company-logo {
            max-height: 74px;
            max-width: 240px;
            object-fit: contain;
        }
        .receipt-title {
            font-size: 1.25rem;
            font-weight: 700;
            letter-spacing: .04em;
            text-transform: uppercase;
        }
        .receipt-meta {
            font-size: .9rem;
            color: #475569;
        }
        .amount-negative {
            color: #dc3545;
        }
        .receipt-total {
            font-size: 1.15rem;
        }
        @media print {
            body { background: #fff; }
            .receipt-page {
                max-width: none;
                margin: 0;
                border: 0;
                padding: 0;
            }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body>
<div class="receipt-page">
    <div class="d-flex justify-content-between align-items-start gap-3 border-bottom pb-3 mb-4">
        <div>
            <img src="{{ asset(config('company.logo_path', 'images/aiec-logo.png')) }}" alt="{{ config('company.name', 'AIEC Institute') }}" class="company-logo mb-2">
            <div class="fw-bold">{{ config('company.name', 'AIEC Institute') }}</div>
            @if(config('company.subtitle'))
                <div class="receipt-meta">{{ config('company.subtitle') }}</div>
            @endif
            @foreach(config('company.address_lines', []) as $line)
                @if($line)
                    <div class="receipt-meta">{{ $line }}</div>
                @endif
            @endforeach
            @if(config('company.phone'))
                <div class="receipt-meta">Phone: {{ config('company.phone') }}</div>
            @endif
            @if(config('company.email'))
                <div class="receipt-meta">Email: {{ config('company.email') }}</div>
            @endif
            @if(config('company.website'))
                <div class="receipt-meta">{{ config('company.website') }}</div>
            @endif
        </div>
        <div class="text-end">
            <div class="receipt-title">Fee Receipt</div>
            <div class="receipt-meta">Receipt No: <strong>{{ $receiptLog->receipt_no }}</strong></div>
            <div class="receipt-meta">Generated: {{ $receiptLog->created_at->format('d M Y, h:i A') }}</div>
            <div class="receipt-meta">Generated By: {{ optional($receiptLog->generator)->name ?? optional(auth()->user())->name ?? '--' }}</div>
        </div>
    </div>

    <div class="row g-3 mb-4">
        <div class="col-md-6">
            <div class="text-muted small">Customer</div>
            <div class="fw-semibold">{{ $customer->name }}</div>
            <div class="receipt-meta">PID: {{ $customer->pid }}</div>
            <div class="receipt-meta">Phone: {{ $customer->phone }}</div>
        </div>
        <div class="col-md-6">
            <div class="text-muted small">Case Details</div>
            <div class="receipt-meta">Country: {{ config('crm.countries')[$customer->country] ?? $customer->country ?? '--' }}</div>
            <div class="receipt-meta">Visa: {{ $customer->visa_type ?? '--' }}</div>
            <div class="receipt-meta">Counselor: {{ optional($customer->counselor)->name ?? '--' }}</div>
        </div>
    </div>

    <table class="table table-bordered align-middle">
        <thead class="table-light">
            <tr>
                <th>Purpose</th>
                <th>Added By</th>
                <th>Date</th>
                <th class="text-end">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($fees as $fee)
                @php($isRefund = $fee->isRefund())
                <tr>
                    <td>{{ $isRefund ? 'Refund - ' : '' }}{{ $fee->purpose }}</td>
                    <td>{{ optional($fee->user)->name ?? '--' }}</td>
                    <td>{{ optional($fee->created_at)->format('d M Y') }}</td>
                    <td class="text-end {{ $isRefund ? 'amount-negative' : '' }}">
                        {{ $isRefund ? '- ' : '' }}{{ number_format((float) $fee->amount, 2) }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="text-center text-muted">No fees or refunds recorded.</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3" class="text-end receipt-total">Total</th>
                <th class="text-end receipt-total {{ $total < 0 ? 'amount-negative' : '' }}">
                    {{ $total < 0 ? '- ' : '' }}{{ number_format(abs((float) $total), 2) }}
                </th>
            </tr>
        </tfoot>
    </table>

    <div class="d-flex justify-content-end gap-2 mt-4 no-print">
        <button type="button" class="btn btn-outline-secondary" onclick="window.close()">Close</button>
        <button type="button" class="btn btn-primary" onclick="window.print()">Print</button>
    </div>
</div>

<script>
window.addEventListener('load', function () {
    window.print();
});
</script>
</body>
</html>
